Update test10.yml

diff --git a/.github/workflows/test10.yml b/.github/workflows/test10.yml
--- a/.github/workflows/test10.yml
+++ b/.github/workflows/test10.yml
@@ -1,56 +1,41 @@
 name: Caracteres especiais
 on:
-  pull_request:
-    types:
-      - opened
-      - synchronize
-      - reopened
-      - edited
+  push:
+    branches:
+      - main
 
 jobs:
   validar-caracteres:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout do repositório
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
+      - name: Checkout do repositório
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-    - name: Configurar variável de ambiente GH_TOKEN
-      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
+      - name: Configurar variável de ambiente GH_TOKEN
+        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
 
-    - name: Obter lista de arquivos alterados
-      run: |
-        set -x
-        # Obter a lista de arquivos alterados no pull request
-        arquivos_alterados=($(git diff --name-only HEAD^1))
+      - name: Obter lista de arquivos alterados
+        run: |
+          set -x
+          # Obter a lista de arquivos alterados no push
+          arquivos_alterados=($(git diff --name-only HEAD^1))
 
-        # Adicionar ação para validar encoding
-        for arquivo in "${arquivos_alterados[@]}"; do
-          #encoding_info=$(chardetect "$arquivo" | cut -d ' ' -f 2)
-          encoding_info=$(file -i "$arquivo" | awk -F "=" '{print $2}' | tr -d ' ')
-          
-          if [ "$encoding_info" != "us-ascii" ] && [ "$encoding_info" != "utf-8" ] && [ "$encoding_info" != "binary" ]; then
-          echo ">>>>>>>>>>>>>>>> $encoding_info"
-          echo "::error::Existe arquivo com caracteres especiais no PR"
-          saida+="$arquivo"$'\n'
-          encontrado=true
-          fi
+          # Adicionar ação para validar encoding
+          for arquivo in "${arquivos_alterados[@]}"; do
+            encoding_info=$(file -i "$arquivo" | awk -F "=" '{print $2}' | tr -d ' ')
+            
+            if [ "$encoding_info" != "us-ascii" ] && [ "$encoding_info" != "utf-8" ] && [ "$encoding_info" != "binary" ]; then
+              echo ">>>>>>>>>>>>>>>> $encoding_info"
+              echo "::error::Existe arquivo com caracteres especiais no push"
+              saida+="$arquivo"$'\n'
+              encontrado=true
+            fi
           done
-        
-        if [ "$encontrado" == true ]; then
-        SLACK_MESSAGE="Existe arquivo com caracteres especiais no PR ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})"
-        curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
-        PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
-        REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
-        REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
-        AUTHOR_NAME=${{ github.event.pull_request.user.login }}
-        gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
-        Existe arquivo com caracteres especiais no PR.
-        Por favor, corrija o(s) arquivo(s) e faça um novo commit."
-        exit 1
-        fi
-
-
-        
+          
+          if [ "$encontrado" == true ]; then
+            echo "Arquivo(s) com caracteres especiais encontrados. Commit bloqueado."
+            exit 1
+          fi
