Update test17.yml

diff --git a/.github/workflows/test17.yml b/.github/workflows/test17.yml
--- a/.github/workflows/test17.yml
+++ b/.github/workflows/test17.yml
@@ -9,40 +9,75 @@ on:
 
 jobs:  
   validar-encoding:
-   runs-on: ubuntu-latest
-   steps:
-    - name: Checkout do repositório
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    - name: Configurar variável de ambiente GH_TOKEN
-      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
-    - name: Obter lista de arquivos alterados
-      run: |
-        BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
-        arquivos_alterados=($(git diff --name-only $BASE_COMMIT ${{ github.sha }}))
-        for arquivo in "${arquivos_alterados[@]}"; do
-          encoding_info=$(file -i "$arquivo" | awk -F "=" '{print $2}' | tr -d ' ')
-          if [ "$encoding_info" != "us-ascii" ] && [ "$encoding_info" != "utf-8" ] && [ "$encoding_info" != "iso-8859-1" ]; then
-            echo ">>>>>>>>>>>>>>>> $encoding_info"
-            echo "::error::O arquivo $arquivo não está codificado como UTF-8."
-            saida+="$arquivo"$'\n'
-            encontrado=true
-          fi
-        done
-        
-        if [ "$encontrado" == true ]; then
-          SLACK_MESSAGE="UTF-8 Encoding Error PR ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})
-          Existe arquivo que não está codificado como UTF-8.\n$saida"
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
-          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
-          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
-          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
-          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
-          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
-          Existe arquivo que não está codificado como UTF-8.
-          $saida Por favor, corrija o encoding e faça um novo commit."
-          exit 1
-        else
-          echo "PR OK"
-        fi
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout do repositório
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Configurar variável de ambiente GH_TOKEN
+        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Obter lista de arquivos alterados
+        run: |
+          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
+          arquivos_alterados=($(git diff --name-only $BASE_COMMIT ${{ github.sha }}))
+          for arquivo in "${arquivos_alterados[@]}"; do
+            encoding_info=$(file -i "$arquivo" | awk -F "=" '{print $2}' | tr -d ' ')
+            if [ "$encoding_info" != "us-ascii" ] && [ "$encoding_info" != "utf-8" ] && [ "$encoding_info" != "iso-8859-1" ]; then
+              echo ">>>>>>>>>>>>>>>> $encoding_info"
+              echo "::error::O arquivo $arquivo não está codificado como UTF-8."
+              saida+="$arquivo"$'\n'
+              encontrado=true
+            fi
+          done
+
+          if [ "$encontrado" == true ]; then
+            SLACK_MESSAGE="UTF-8 Encoding Error PR ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\nExiste arquivo que não está codificado como UTF-8.\n$saida"
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+            PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
+            REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
+            REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
+            AUTHOR_NAME=${{ github.event.pull_request.user.login }}
+            gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME\nExiste arquivo que não está codificado como UTF-8.\n$saida\nPor favor, corrija o encoding e faça um novo commit."
+            exit 1
+          else
+            echo "PR OK"
+
+  validar-encoding2:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout do repositório
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Configurar variável de ambiente GH_TOKEN
+        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
+
+      - name: Obter lista de arquivos alterados
+        run: |
+          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
+          arquivos_alterados=($(git diff --name-only $BASE_COMMIT ${{ github.sha }}))
+          for arquivo in "${arquivos_alterados[@]}"; do
+            encoding_info=$(file -i "$arquivo" | awk -F "=" '{print $2}' | tr -d ' ')
+            if [ "$encoding_info" != "us-ascii" ] && [ "$encoding_info" != "utf-8" ] && [ "$encoding_info" != "iso-8859-1" ]; then
+              echo ">>>>>>>>>>>>>>>> $encoding_info"
+              echo "::error::O arquivo $arquivo não está codificado como UTF-8."
+              saida+="$arquivo"$'\n'
+              encontrado=true
+            fi
+          done
+
+          if [ "$encontrado" == true ]; then
+            SLACK_MESSAGE="UTF-8 Encoding Error PR ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\nExiste arquivo que não está codificado como UTF-8.\n$saida"
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+            PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
+            REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
+            REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
+            AUTHOR_NAME=${{ github.event.pull_request.user.login }}
+            gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME\nExiste arquivo que não está codificado como UTF-8.\n$saida\nPor favor, corrija o encoding e faça um novo commit."
+            exit 1
+          else
+            echo "PR OK"
