Update test9.yml

diff --git a/.github/workflows/test9.yml b/.github/workflows/test9.yml
--- a/.github/workflows/test9.yml
+++ b/.github/workflows/test9.yml
@@ -70,4 +70,20 @@ jobs:
 
         echo ">>>>>>>depois do for>>>>>>>>>>>>> $encontrada"
 
-       
+        if [ "$encontrada" == false ]; then
+          echo "::error::Criação de índice sem tablespace"
+          SLACK_MESSAGE="Criação de índice sem tablespace no PR - ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n$saida"
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
+          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
+          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
+          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
+          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
+          Criação de índice sem tablespace
+          ${saida}Por favor revisar."
+          exit 1
+        else
+          echo "PR OK"
+        fi
+        fi
+        fi
